name: Main

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python v3.8.6
        uses: actions/setup-python@v3
        with:
          python-version: '3.8.6'

      - name: Run a one-line script
        run: python --version
